name: DemonMarket
main: com.tining.demonmarket.Main
version: 1.0
# YAML 中的注释，一行有效
# 以上是插件基本信息，以下是命令注册
depend:
  - Vault
commands:
  market: # 命令的基本名，请不要使用奇怪的字符！
    aliases: # 别名，方便玩家使用
      - mt
    usage: |
      /mt sell 出售手里的物品
      /mt sell all 出售背包里当前所有与手中相同的物品
    description: Buy or sell some item in player's inventory # 描述
    permission: demonmarket.use
    permission-message: You need to have the permission to use this command. Please contact your server OP. # 无权限返回的消息，通常不用

permissions:
  demonmarket.use:
    description: market use permission
    default: true