name: GlobalMarket
main: com.ender.globalmarket.Main
version: 1.0
api-version: 1.18
# YAML 中的注释，一行有效
# 以上是插件基本信息，以下是命令注册
depend:
  - Vault
loadbefore:
  - Value
commands:
  globalmarket: # 命令的基本名，请不要使用奇怪的字符！
    aliases: # 别名，方便玩家使用
      - gm
    usage: | 
      /globalmarket gui 打开图形化市场
      /globalmarket money 查看账户余额
      /globalmarket list 查看可交易物品列表
      /globalmarket sell <物品名称(格式minecraft:xxx)> <数量> 出售一定数量物品，数量输入all可以出售所有此种物品
      /globalmarket buy <物品名称(格式minecraft:xxx)> <数量> 购买一定数量物品
      /globalmarket calc [buy/sell] <物品名称(格式minecraft:xxx)> <数量> 计算出售或购买一定数量物品的价格
      /globalmarket help 查看命令提示
      /gm 命令可简写为gm
    description: Buy or sell some item in player's inventory # 描述
    permission: globalmarket.use
    permission-message: You need to have the permission to use this command. Please contact your server OP. # 无权限返回的消息，通常不用
  globalmarketadmin:
    aliases:
      - gma
    usage: |
      /globalmarketadmin set <库存> <最高价格> <市场稳定度> <物品名称> 创建新的可交易物品
      /globalmarketadmin remove <物品名称> 移除可交易物品
    description: Admin command for globalmarket
    permission: globalmarket.admin
    permission-message: You need to have the permission to use this command. Please contact your server OP. # 无权限返回的消息，通常不用

permissions:
  globalmarket.admin:
    description: Admin
    default: op
  globalmarket.use:
    description: market use permission
    default: true